
-- SQL schema for ICRISAT cleaned table
CREATE TABLE icrisat_district_cleaned (
    id SERIAL PRIMARY KEY,
    state TEXT,
    district TEXT,
    year INTEGER,
    rice_area_ha DOUBLE PRECISION,
    rice_prod_t DOUBLE PRECISION,
    rice_yield DOUBLE PRECISION,
    rice_area_ha_missing BOOLEAN,
    rice_prod_t_missing BOOLEAN,
    rice_yield_missing BOOLEAN
);

-- Sample INSERTs (first 100 rows)
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1966, 548000.0, 185000.0, 337.59, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1967, 547000.0, 409000.0, 747.71, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1968, 556300.0, 468000.0, 841.27, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1969, 563400.0, 400800.0, 711.4, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1970, 571600.0, 473600.0, 828.55, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1971, 581800.0, 412900.0, 709.69, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1972, 582200.0, 381000.0, 654.41, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1973, 600000.0, 471900.0, 786.5, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1974, 587400.0, 219000.0, 372.83, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1975, 598300.0, 454000.0, 758.82, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1976, 593600.0, 327100.0, 551.04, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1977, 600700.0, 572400.0, 952.89, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1978, 612500.0, 362200.0, 591.35, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1979, 616800.0, 330600.0, 535.99, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1980, 634900.0, 515600.0, 812.1, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1981, 630000.0, 506900.0, 804.6, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1982, 627900.0, 513300.0, 817.49, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1983, 626700.0, 711000.0, 1134.51, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1984, 632200.0, 563800.0, 891.81, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1985, 630800.0, 699800.0, 1109.38, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1986, 643000.0, 525000.0, 816.49, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1987, 648000.0, 523000.0, 807.1, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1988, 652700.0, 549700.0, 842.19, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1989, 660200.0, 457300.0, 692.67, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1990, 682900.0, 806800.0, 1181.43, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1991, 680800.0, 773600.0, 1136.31, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1992, 688000.0, 777300.0, 1129.8, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1993, 703600.0, 876700.0, 1246.02, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1994, 726800.0, 967900.0, 1331.73, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1995, 723300.0, 1052000.0, 1454.44, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1996, 710900.0, 917200.0, 1290.2, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1997, 735700.0, 837500.0, 1138.37, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1998, 786510.0, 684620.0, 870.45, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 1999, 769790.0, 963040.0, 1251.04, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2000, 748760.0, 467890.0, 624.89, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2001, 756260.0, 978690.0, 1294.13, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2002, 753410.0, 484900.0, 643.6, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2003, 766580.0, 1145820.0, 1494.73, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2004, 775990.0, 984310.0, 1268.46, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2005, 775990.0, 984310.0, 1268.46, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2006, 781700.0, 1177100.0, 1505.81, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2007, 799890.0, 1095840.0, 1369.98, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2008, 803370.0, 704090.0, 876.42, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2009, 789040.0, 622050.0, 788.37, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2010, 777920.0, 1319180.0, 1695.77, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2011, 806550.0, 1416480.0, 1756.23, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2012, 807070.0, 1534220.0, 1900.97, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2013, 819440.0, 1296240.0, 1581.86, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2014, 834870.0, 1444240.0, 1729.89, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2015, 817680.0, 880600.0, 1076.95, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2016, 858910.0, 1791660.0, 2085.96, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Durg', 2017, 841130.0, 983210.0, 1168.92, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1966, 406000.0, 261000.0, 642.86, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1967, 414000.0, 319000.0, 770.53, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1968, 423200.0, 294000.0, 694.71, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1969, 429100.0, 329000.0, 766.72, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1970, 437700.0, 316800.0, 723.78, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1971, 445600.0, 366600.0, 822.71, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1972, 443100.0, 285800.0, 645.0, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1973, 450500.0, 364300.0, 808.66, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1974, 451600.0, 302900.0, 670.73, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1975, 458300.0, 407900.0, 890.03, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1976, 459600.0, 296100.0, 644.26, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1977, 473400.0, 430400.0, 909.17, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1978, 490400.0, 402200.0, 820.15, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1979, 497500.0, 309200.0, 621.51, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1980, 519400.0, 391800.0, 754.33, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1981, 523500.0, 389300.0, 743.65, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1982, 527700.0, 372400.0, 705.7, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1983, 538000.0, 408000.0, 758.36, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1984, 533400.0, 395600.0, 741.66, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1985, 555400.0, 834300.0, 1502.16, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1986, 556000.0, 403000.0, 724.82, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1987, 555000.0, 382000.0, 688.29, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1988, 572800.0, 553200.0, 965.78, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1989, 571700.0, 544700.0, 952.77, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1990, 579000.0, 561900.0, 970.47, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1991, 582300.0, 624300.0, 1072.13, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1992, 584400.0, 533300.0, 912.56, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1993, 605300.0, 603700.0, 997.36, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1994, 609900.0, 604000.0, 990.33, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1995, 619000.0, 589100.0, 951.7, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1996, 644100.0, 670500.0, 1040.99, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1997, 622800.0, 455000.0, 730.57, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1998, 627100.0, 569800.0, 908.63, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 1999, 628470.0, 676200.0, 1075.95, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2000, 628030.0, 523900.0, 834.2, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2001, 633990.0, 922150.0, 1454.52, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2002, 623900.0, 331380.0, 531.14, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2003, 632580.0, 1042750.0, 1648.41, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2004, 635470.0, 788650.0, 1241.05, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2005, 635470.0, 788650.0, 1241.05, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2006, 546540.0, 836540.0, 1530.61, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2007, 626070.0, 927730.0, 1481.83, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2008, 627780.0, 729330.0, 1161.76, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2009, 626660.0, 682460.0, 1089.04, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2010, 621890.0, 1184980.0, 1905.45, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2011, 627730.0, 772880.0, 1231.23, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2012, 637800.0, 1341330.0, 2103.06, FALSE, FALSE, FALSE);
INSERT INTO icrisat_district_cleaned (state,district,year,rice_area_ha,rice_prod_t,rice_yield,rice_area_ha_missing,rice_prod_t_missing,rice_yield_missing) VALUES ('Chhattisgarh', 'Bastar', 2013, 642790.0, 1265910.0, 1969.4, FALSE, FALSE, FALSE);
